### ISSUE TITLE
Latest branch commits breaks when no spider.cfg exists

### ISSUE THREAD

**Issue by artagel** [TorSpider/TorSpider#25]
When you don't have a spider.cfg then you get: 
./TorSpider.py 
CONFIG ERROR

This is because of the order of the imports now, so we need to ensure the spider.cfg check is done first.

**Comment by haxys** [comment]
This issue had to do with my changes to logging. I fixed it. I realized the mistake when I went to sleep last night, but didn't wake up to fix it. 😴
